import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ minHeight: '525px' }} className="p-4">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Doloremque,
        deserunt cupiditate laboriosam ex voluptate accusamus! Excepturi
        mollitia odit, eos aperiam eius libero laudantium amet reprehenderit
        facere nesciunt autem, hic error enim dolores ea aliquid velit dolore
        quam eveniet! Libero, eius. Consectetur vitae impedit earum cupiditate
        amet deserunt ea quos. Vero culpa sed veniam tempore voluptas cum sint
        corrupti? Rerum suscipit sunt vero esse temporibus voluptas alias
        deleniti magni ducimus. Nesciunt soluta, in veritatis beatae quos
        explicabo minus! Vel, ab odio reprehenderit saepe sint, officia illo,
        facilis inventore tenetur fugiat omnis quaerat perferendis incidunt?
        Aliquid voluptas eligendi eaque labore, architecto tempore! Lorem ipsum
        dolor sit amet, consectetur adipisicing elit. Tempore voluptatem quos
        aspernatur? Neque consectetur praesentium possimus commodi
        exercitationem cum dicta inventore iste nisi architecto voluptatem
        tenetur aspernatur magni debitis error repudiandae, explicabo minus, nam
        quia cumque voluptates esse corporis beatae. Perspiciatis tenetur
        consectetur, itaque soluta facere ipsum ipsa deserunt ullam ducimus at
        placeat ex sint eos molestiae molestias esse quas suscipit magnam odio
        temporibus. Labore maxime possimus quam natus dolore doloremque
        excepturi, est nisi! Iste eius, magnam libero quas fugit labore.
        Pariatur blanditiis ullam qui, distinctio, quisquam voluptates neque non
        sint cupiditate ducimus, obcaecati dolorum aut? Delectus blanditiis rem
        tenetur a autem eum impedit, esse debitis molestiae quidem eos
        reprehenderit laudantium iusto quaerat quas aliquid dolores suscipit,
        numquam aperiam alias? Dolorem consectetur, delectus facilis sed natus
        voluptatum perspiciatis dolorum nam ut ipsam amet possimus earum.
        Temporibus cupiditate voluptatibus laboriosam ipsa soluta quo explicabo
        voluptas vel placeat nemo modi nostrum, at velit impedit. Voluptatem
        laboriosam, rem eum animi obcaecati facere voluptates dolore velit ea
        repudiandae quas est corporis, perspiciatis sed sapiente harum dolorum
        doloribus. Perspiciatis dignissimos distinctio laudantium eligendi,
        placeat necessitatibus eum assumenda, iure expedita vero aliquam, illum
        atque reiciendis sint obcaecati ex officiis eaque iste cupiditate sit
        natus a. Consectetur id minus nam natus doloremque, ullam hic ipsam
        deserunt corporis modi expedita unde officia, ex alias ut rerum
        excepturi quae harum reprehenderit cupiditate sapiente. Eos, soluta
        dolore deleniti vero error nostrum sunt iure illum nobis ipsum similique
        voluptatibus vel incidunt veritatis earum sapiente dicta cumque minus
        corrupti tenetur. Fugiat libero eius aut, vel, ipsam in cum quo
        accusamus ab sequi eum officiis quaerat. Architecto quasi nisi ullam
        quisquam qui at porro ut, molestiae placeat harum inventore, asperiores
        itaque! Iusto laborum nisi molestias molestiae eaque. Minima similique
        voluptatem, nulla natus rem tempore, laborum exercitationem veritatis
        itaque quas, provident voluptatibus quam dolorum. Quo autem tempore
        tempora doloribus laborum, quisquam molestias recusandae impedit numquam
        vitae accusamus, sint ut reiciendis quas at mollitia vero eos, excepturi
        ipsa suscipit sed. Quas laudantium possimus atque facere, adipisci
        ipsam, quod provident unde reprehenderit, vero qui optio delectus? Ipsa
        nisi enim aliquid, totam corporis fugit delectus animi nesciunt iure
        voluptate error veritatis tempore sequi. Rerum, atque alias dolores ut
        labore dignissimos obcaecati, magnam voluptas maxime cupiditate iure qui
        molestias praesentium officiis expedita ipsa delectus animi commodi
        sapiente ex accusamus ducimus et quod quis. Inventore eligendi hic
        voluptas reprehenderit reiciendis pariatur vero delectus ducimus
        tenetur. Voluptatibus beatae eos placeat sapiente laudantium, ab saepe
        eum? Itaque impedit, cupiditate commodi est aliquid necessitatibus
        expedita voluptatum similique consequatur, natus molestias nostrum
        numquam sapiente quasi iste modi quas aspernatur neque dicta! Eos minus
        corporis vero laboriosam assumenda, et enim ducimus autem recusandae
        quaerat sit quam illo. Odit, architecto nemo. Cumque non labore nostrum
        hic sequi, aut exercitationem consectetur, alias adipisci eius illum,
        tempore excepturi! Adipisci a totam magni iusto ad error sunt quod nobis
        officiis. Rerum, quas deserunt. Veniam enim dolor excepturi molestias
        quia modi exercitationem ea laborum obcaecati, quis impedit. Magnam
        voluptates atque iusto quos totam harum? Deserunt iste excepturi sint
        perferendis.
      </main>
    </div>
  );
}
