import Image from 'next/image';
import { Inter } from 'next/font/google';
import Head from 'next/head';

// token: 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

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Don't Die Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex min-h-screen flex-col items-center justify-between p-24 ${inter.className}`}
      >
        <h1 style={{ fontSize: '3rem' }}>Don't Die Admin</h1>
      </main>
    </div>
  );
}
